<?php

namespace DA\PlatformBundle\Repository;
use DateTime;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpFoundation\Request;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function _getAvertAll($paginator, $page, $nbPerPage)
    {
        $query = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->orderBy('a.date', 'DESC')
            ->getQuery()
            ->getResult();

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */

        return $paginator->paginate(
            $query,
            $page,
            $nbPerPage
        );
    }

    public function _getAvert($id)
    {
       $query = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->leftJoin('a.applications', 'app')
            ->addSelect('app')
            ->leftJoin('a.advert_skills', 'ads')
            ->addSelect('ads')
            ->leftJoin('ads.skill', 'adss')
            ->addSelect('adss')
            ->where('a.id = :id')
            ->setParameter('id', $id);
        return $query
                    ->getQuery()
                    ->getSingleResult();
    }

    public function _getAdvertBeforeDate($days)
    {
        return	$this->createQueryBuilder('a')
            ->where('a.updatedAt <=	:date')
            ->orWhere('a.updatedAt IS	NULL AND a.date	<=	:date')
            ->andWhere('a.applications	IS	EMPTY')
            ->setParameter('date',	$days)
            ->getQuery()
            ->getResult()
        ;
    }
}
