<?php

namespace DA\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function _getApplicationsWhithAdvert($limit)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.advert', 'adv')
            ->addSelect('adv');

        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
