services:
    your.user_login_route_listener:
        class: DA\UserBundle\Event\UserLoginRouteListener
        arguments:
            - "@security.token_storage"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
