services:
#    da_platform.example:
#        class: DA\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    da_platform.antispam:
        class: DA\PlatformBundle\Antispam\DAAntispam
        arguments: ["@mailer", "%locale", 50]

    da_platform.email.application_mailer:
        class: DA\PlatformBundle\Email\ApplicationMailer
        arguments: ["@mailer"]

    da_platform.email.advert_delete_mailer:
        class: DA\PlatformBundle\Email\AdvertDeleteMailer
        arguments: ["@mailer"]

    da_platform.doctrine_listener.application_creation:
        class: DA\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments: ["@da_platform.email.application_mailer"]
        tags:
            - {name: doctrine.event_listener, event: postPersist}

    da_platform.doctrine_listener.advert_creation:
        class: DA\PlatformBundle\DoctrineListener\AdvertCreationListener
        arguments: ["@da_platform.email.advert_delete_mailer"]
        tags:
            - {name: doctrine.event_listener, event: postRemove}

    da_platform.purger.advert:
        class: DA\PlatformBundle\Purger\AdvertPuger
        arguments: ["@doctrine.orm.entity_manager"]

    # src/OC/PlatformBundle/Resources/config/services.yml

    da_platform.validator.antiflood:
        class: DA\PlatformBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }