services:
#    da_platform.example:
#        class: DA\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    da_platform.antispam:
        class: DA\PlatformBundle\Antispam\DAAntispam
        arguments: ["@mailer", "%locale", 50]

    da_platform.email.application_mailer:
        class: DA\PlatformBundle\Email\ApplicationMailer
        arguments: ["@mailer"]

    da_platform.doctrine_listener.application_creation:
        class: DA\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments: ["@da_platform.email.application_mailer"]
        tags:
            - {name: doctrine.event_listener, event: postPersist}