services:
#    da_platform.example:
#        class: DA\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    da_platform.antispam:
        class: DA\PlatformBundle\Antispam\DAAntispam
        arguments: ["@mailer", "%locale", 50]